internship/internship/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    path('account/login',views.LoginView.as_view(template_name="registration/login.html"),name='login'),
    path('account/logout',views.LogoutView.as_view(template_name="home.html"),name='logout',kwargs={'next_page':'home'}),
]

internship/myapp/urls.py
from django.urls import path,re_path
app_name='myapp'
from myapp import views
urlpatterns=[
             path('',views.home,name="home"),
             path('form_host',views.CreateHostView.as_view(),name='host_form'),
             path('hosts',views.HostList.as_view(),name='host_list'),
             path('form_visitor',views.CreateVisitorView.as_view(),name='visitor_form'),
             path('visit',views.VisitorList.as_view(),name='visit_list'),
             re_path(r'^(?P<pk>\d+)/update/$',views.checkout,name="checked"),
             re_path(r'^(?P<pk>\d+)/mail/$',views.sendmail,name="sendmail"),


]

internship/myapp/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
import datetime
# Create your models here.
from django.urls import reverse
class Host(models.Model):
    host_name = models.CharField(max_length=30,blank=False)
    email = models.EmailField(max_length=254)
    phone_no = PhoneNumberField(blank=True, help_text='Contact Phone Number')
    def get_absolute_url(self):
        return reverse('myapp:host_list')
    def __str__(self):
        return self.host_name
class Visitor(models.Model):
    host=models.ForeignKey('Host',on_delete = models.CASCADE,related_name='visitor')
    visitor_name = models.CharField(max_length=30,blank=False)
    email = models.EmailField(max_length=254)
    phone_no = PhoneNumberField(blank=True, help_text='Contact phone number')
    date = models.DateField(auto_now=True)
    check_in = models.TimeField(auto_now_add=True)
    check_out=models.TimeField(null=True,blank=True)

    def checking_out(self):
        self.check_out = datetime.datetime.now().time()
        self.save()
    def get_absolute_url(self):
        return reverse('myapp:visit_list')
    def __str__(self):
        return self.visitor_name

internship/myapp/forms.py
from django import forms
from myapp.models import Host,Visitor


class HostForm(forms.ModelForm):
    #meta class is used to directly take entry of a form to given models
    class Meta():
        model=Host
        fields=('host_name','email','phone_no')

class VisitorForm(forms.ModelForm):
    #meta class is used to directly take entry of a form to given models
    class Meta():
        model=Visitor
        fields=('host','visitor_name','email','phone_no')

internship/myapp/views.py
from django.shortcuts import render
from django.views.generic import (DeleteView,TemplateView,ListView,DetailView,CreateView,UpdateView)
from django.contrib.auth.mixins import LoginRequiredMixin
from myapp.models import Host,Visitor
from myapp.forms import HostForm,VisitorForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core.mail import EmailMessage
import datetime
from django.core.mail import send_mail
from django.conf import settings
import urllib.request
import urllib.parse
# Create your views here.
def home(request):
    #Host.objects.all().delete()
    #Visitor.objects.all().delete()
    return render(request,'home.html')
class CreateHostView(LoginRequiredMixin,CreateView):
    login_url='/login/'
    #redirect_field_name = "host_form.html"
    form_class = HostForm
    model = Host
class HostList(ListView):
    model = Host
    context_object_name = 'host'
class CreateVisitorView(CreateView):

    #redirect_field_name = "host_form.html"
    form_class = VisitorForm
    model = Visitor
    def get_success_url(self):
        print(self.object.id)
        return reverse('myapp:sendmail',args=(self.object.id,))



def sendSMS(numbers,message):
    data =  urllib.parse.urlencode({'apikey': 'mjQq3UioT04-Yc1CskXZn3kmgHM5arOJNt4g2hP5CG', 'numbers': numbers,
        'message' : message,})
    data = data.encode('utf-8')
    request = urllib.request.Request("https://api.textlocal.in/send/?")
    f = urllib.request.urlopen(request, data)
    fr = f.read()
    return(fr)






def sendmail(request,pk):
    time = Visitor.objects.get(pk=pk)
    subject = 'Visitor Came To Meet'
    #message="Hi"
    message = 'Name: ' +time.visitor_name+"\n"+'Phone :'+str(time.phone_no) +"\n"+"Checkin Time: "+str(time.check_in)
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [str(time.host.email),]
    send_mail( subject, message, email_from, recipient_list )
    resp =  sendSMS(str(time.host.phone_no),message)
    print (resp)
    return HttpResponseRedirect(reverse('myapp:visit_list'))
class VisitorList(ListView):
    model = Visitor
    context_object_name = 'visit'
    def get_queryset(self):
        return Visitor.objects.order_by('-date','-check_in')

def checkout(request,pk):
    time = Visitor.objects.get(pk=pk)
    time.check_out=datetime.datetime.now().strftime('%H:%M:%S')
    time.save()

    subject = 'Thanks for Visiting'
    message = 'Name: ' +time.visitor_name+"\n"+'Phone :'+str(time.phone_no) +"\n"+"Checkin Time: "+str(time.check_in)+"\n"+'Checkout Time: '+str(time.check_out)+"\n"+"Host Name: "+str(time.host.host_name)
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [str(time.email),]
    send_mail( subject, message, email_from, recipient_list )
    print(message)
    resp =  sendSMS(str(time.phone_no),message)
    print (resp)


    return HttpResponseRedirect(reverse('myapp:visit_list'))

internship/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>HOME</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Abel&display=swap" rel="stylesheet">
  </head>
  <body>

<div class="container">


    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="font-family: 'Josefin Sans', sans-serif;">
      Entry Management
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:visitor_form' %}">Visitor <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'myapp:host_list' %}">Hosts <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item active">

          <a class="nav-link" href="{% url 'myapp:host_form' %}"> Add Host </a>
          </li>

          {% endif %}
          <li class="nav-item active">

            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">LogOut <span class="sr-only">(current)</span></a>
            {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login <span class="sr-only">(current)</span></a>
            {% endif %}
          </li>

          <li class="nav-item active">

          <a class="nav-link" href="{% url 'myapp:visit_list' %}"> Visited </a>
          </li>
        </ul>

      </div>
    </nav>
    </div>


<div class="container">
  {% block content %}
  <div class="jumbotron">
         <h1 style='font-family: 'Josefin Sans', sans-serif;'>Entry management software</h1>
         <h2>Problem Statement</h2>
         
         <p>We need an application, which can capture the Name, email address, phone no of the visitor and
same information also needs to be captured for the host on the front end.
At the back end, once the user enters the information in the form, the backend should store.</p>


<h2>Solution:</h2>
<p>We have created a single admin which can add Host, whenver any visitor comes to visit a host, he/she can choose the host whom they wants to meet. After the visitor fills the form, the host will recieve the email and sms regarding the details of the visitor.</p>
       </div>
  {% endblock %}

</div>




  </body>
</html>

internship/templates/myapp/host_form.html
{% extends 'home.html' %}
{% block content %}
{% load bootstrap3 %}

<h1 style="font-family: 'Josefin Sans', sans-serif;" >Create New Host</h1>
    <form class="post-form"  method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-primary">Create Host</button>

    </form>




{% endblock %}

internship/templates/myapp/host_list.html
{% extends 'home.html' %}
{% block content %}


<ul class="list-group" style="font-family: 'Josefin Sans', sans-serif;">
    <li><h1 style="margin-left:10em;">Host to Meet</h1></li>
</ul>
  <hr>
  <table  border="1" style="padding: 15px; border-spacing: 5px; font-family: 'Abel', sans-serif;" class="table table-hover">
                    <tr style="text-align:center;">
                      <th scope="col">Name</th>
                      <th scope="col">Email ID</th>
                      <th scope="col">Contact No</th>
                    </tr>

                    {% for i in host %}
                    <tr style="text-align:center;">
                      <td>{{ i.host_name }}</td>
                      <td>{{ i.email }}</td>
                      <td>{{ i.phone_no }}</td>
                    </tr>

                    {% endfor %}
  </table>




{% endblock %}

internship/templates/myapp/visitor_form.html
{% extends 'home.html' %}
{% block content %}
{% load bootstrap3 %}

<h1>Visitor</h1>
    <form class="post-form"  method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          <button type="submit" class="btn btn-primary">Submit</button>

    </form>




{% endblock %}

internship/templates/myapp/visitor_list.html
{% extends 'home.html' %}
{% block content %}


<ul class="list-group" style="font-family: 'Josefin Sans', sans-serif;">
    <li><h1 style="margin-left:10em;">Visited Visitors</h1></li>
</ul>
  <hr>
  <table  border="1" style="padding: 15px; border-spacing: 5px;font-family: 'Abel', sans-serif;" class="table table-hover">
                    <tr style="text-align:center;">
                      <th scope="col">Date</th>
                      <th scope="col">Name</th>
                      <th scope="col">Contact No</th>
                      <th scope="col">Visited Place</th>
                      <th scope="col">Check In</th>
                      <th scope="col">Check Out</th>
                    </tr>

                    {% for i in visit %}
                    <tr style="text-align:center;">
                      <td>{{ i.date }}</td>
                      <td>{{ i.visitor_name }}</td>
                      <td>{{ i.phone_no }}</td>
                      <td>{{ i.host.host_name }}</td>
                      <td>{{ i.check_in }}</td>
                      {% if i.check_out == None %}
                      <td><a href="{% url 'myapp:checked' pk=i.pk %}">Check Out</a></td>
                      {% else %}
                      <td>{{ i.check_out }}</td>
                      {% endif %}
                    </tr>

                    {% endfor %}
  </table>




{% endblock %}